<a href="https://colab.research.google.com/github/Laxmi9136/Java-oops-short-notes/blob/main/pythonnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#python Numpy

In [5]:
import numpy as np #alias-nickname


In [6]:
arr0d = np.array(24)
arr0d

array(24)

In [7]:
arr1d = np.array([1,2,3,4,5])
arr1d #1-D

array([1, 2, 3, 4, 5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [8]:
arr2d = np.array([[1,2]]),([[3,4]])
arr2d

(array([[1, 2]]), [[3, 4]])

In [9]:
arr3d = np.array([[[2,5],[6,8]],[[10,11],[34,54]]])#3-D
arr3d

array([[[ 2,  5],
        [ 6,  8]],

       [[10, 11],
        [34, 54]]])

In [ ]:
#DIMENSION
#IS THE DEPTH OF AN ARRAY

In [ ]:
#NUMPY ATTRIBUTES

In [10]:
arr0d.shape,arrid.shape,arr2d.shape,arr3d.shape

NameError: name 'arrid' is not defined

In [ ]:
# size
print(arr1d.size)
print(arr3d.size)

NameError: name 'arr1d' is not defined

In [ ]:
#dtype

print(arr1d.dtype)
print(arr3d.dtype)

NameError: name 'arr1d' is not defined

In [ ]:
#ndim

print(arr3d.ndim)

NameError: name 'arr3d' is not defined

In [ ]:
###NUMPY STORES SAME TYPE OF DATA ..IT IS HOMOGENEOUES IN NATURE


In [ ]:
arr=np.array([10,34,43,54,35,36,"apple"])
arr

array(['10', '34', '43', '54', '35', '36', 'apple'], dtype='<U21')

In [ ]:
arr=np.array([10,34,24,564,63],dtype=bool)
arr

array([ True,  True,  True,  True,  True])

In [ ]:
arr=np.array([10,34,24,564,63],dtype=str)
arr

array(['10', '34', '24', '564', '63'], dtype='<U3')

In [ ]:
#YOU CAN ALSR SPECIFY  THE MEMORY SIZR OF THE DATA TYPE

In [ ]:
arr=np.array([10,34,24,5,63],dtype='int8')

In [ ]:
#INDEXING AND SLICING

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]

np.int64(1)

In [ ]:
arr[0],arr[-1]

(np.int64(1), np.int64(5))

In [ ]:
#SLICING


In [ ]:
arr[1:4]

array([2, 3, 4])

In [ ]:
###2-D ARRAY

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[10,0,1,100,8],[1,1,7,3,9]])
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,   0,   1, 100,   8],
       [  1,   1,   7,   3,   9]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0][0]

np.int64(1)

In [ ]:
arr[2][3]

np.int64(100)

In [ ]:
arr[0:,0:]

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,   0,   1, 100,   8],
       [  1,   1,   7,   3,   9]])

In [ ]:
arr[0::2,0:]

array([[  1,   2,   3,   4,   5],
       [ 10,   0,   1, 100,   8]])

In [ ]:
arr[0::2,0::2]

array([[ 1,  3,  5],
       [10,  1,  8]])

In [ ]:
arr[0,-1],[0,-1]


(np.int64(5), [0, -1])

In [ ]:
#

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#FULL()

In [ ]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#ARRAY OPERATION

In [ ]:
  arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
  arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [ ]:
arr+2

array([[ 3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11]])

In [ ]:
arr**2

array([[ 1,  4,  9, 16, 25],
       [25, 36, 49, 64, 81]])

In [ ]:
arr%3

array([[1, 2, 0, 1, 2],
       [2, 0, 1, 2, 0]])

#RANDOM ARRAY GENERATION


**bold text**

In [11]:
np

<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>

In [12]:
np.random.rand()

0.13950509289012192

In [13]:
np.random.rand(3)

array([0.84661912, 0.28648596, 0.09578252])

In [15]:
np.random.rand(3,2)

array([[0.26657344, 0.68560208],
       [0.37917453, 0.35640449],
       [0.25148538, 0.51670166]])

#VISUALIZATION OF RAND GENERTED DATA



#NORMAL DATA DISTRIBUTION

In [16]:
np.random.randn(10)

array([-0.71184691,  0.26392084,  1.29444263, -0.47375315, -1.5524768 ,
        1.29397727,  1.38452724,  0.85610879, -0.68443155, -0.2418093 ])

RANDINT()

In [17]:
np.random.randint(10,20)

11

In [20]:
np.random.randint(10,20,(3,3))

array([[19, 18, 18],
       [15, 10, 10],
       [11, 16, 14]])

In [22]:
np.random.randint(10,20,(3,3,2))

array([[[12, 19],
        [19, 12],
        [19, 14]],

       [[15, 10],
        [14, 11],
        [10, 15]],

       [[12, 15],
        [11, 11],
        [18, 12]]])

#HOW TO REPRODUCT THE SAME ARRAY AGAIN?